- name: Install httpd
  tags: httpd apache apache2
  package:
    name: httpd
    state: latest 
  when: ansible_os_family == "RedHat"
 
- name: Start and enable httpd.service
  tags: httpd apache apache2
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Change the parameters in idex.html
  tags: httpd apache apache2
  lineinfile:
    path: /var/www/html/index.html
    regexp: "Patko.bily"
    line: " <0> Patko.bily@outlook.com <0>"
    firstmatch: yes
  when: ansible_os_family == "RedHat"
  notify: restart hhtpd
