- name: Install necessary packages
  tags: always
  apt:
    name: 
      - rpm
      - ufw
    state: latest  
  when: ansible_os_family in ["Debian", "Ubuntu"]

- name: Install apache2 
  tags: httpd apache apache2
  apt: 
    name: apache2
    state: latest
  when: ansible_os_family in ["Debian", "Ubuntu"]

- name: Enable UFW
  tags: httpd http apache apache2
  ufw:
    proto: http, https
    port: 80
    rule: allow

- name: Start & Enable apache2
  tags: httpd apache apache2
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family in ["Debian", "Ubuntu"]


- name: Change parameters in idex.html
  tags: apache httpd apache2
  lineinfile:
    path: /var/www/html/index.html
    regexp: "Skusobna webova stranka"
    line: "<title>Moja skusobna stranka webu</title>"
  when: ansible_os_family in ["Debian", "Ubuntu"]
  notify: restart apache2 


