- name: Update repo-package (CentOS)
  tags: always
  package:
    update_only: yes
    update_cache: yes
  when: ansible_os_family == "RedHat"
 
- name: Update repo-package (Debian, Ubuntu)
  tags: always
  package:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family in ["Debian","Ubuntu"]

- name: Copy sudo file SIMON  to remote_servers
  tags: user
  copy:
    src: sudoers_simon
    dest: /etc/sudoers.d/simon
    owner: root
    groups: root
    mode: 0660
   
