- name: Set logging
  ufw:
    logging: on

- name: Deny all incoming traffic
  ufw:
    rule: deny
    direction: incoming

- name: Allow outgoing traffic
  ufw:
    rule: allow
    direction: outgoing
   
- name: allow SSH 
  ufw:
    rule: allow
    name: OpenSSH

- name: limit ssh connections 
  ufw:
    rule: limit 
    port: '22'
    proto: tcp 
     
- name: Allow HTTPS   
  ufw:
    rule: allow
    port: '443'
    protoo: tcp


  

