all_users:
  - pobocka_KE:
      - name: Frantisek
        shell: /bin/bash
        comment: "Žido František"
        group: "branch_ke"
        password: "{{ Frantisek_pw }}"
        password_expire_max: 90
     
      - name: Tomas
        shell: /bin/bash
        comment: "Čechovský Tomáš"
        group: "branch_ke"
        password: "{{ Tomas_pw }}"
        password_expire_max: 90
    
  - admin_users:
      - name: lukas
        shell: /bin/bash
        comment: "user for Ansible"
        password_expire_max: 180
      
      - name: patrik
        shell: /bin/bash
        comment: "Test user, Ansible-practice"
        password_expire_max: 180
       
