- name: Create user for pobocka_KE
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment | default(omit) }}"
    password: "{{ item.password | password_hash('sha512') }}"
    password_expire_max: "{{ item.password_expire_max }}"
  loop: "{{ all_users[0].pobocka_KE }}"

 
- name: Create admin_users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    group: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
    comment: "{{ item.comment | default(omit) }}"
    password_expire_max: "{{ item.password_expire_max }}"
  loop: "{{ all_users[1].admin_users }}"


- name: Force to change the password for a pobocka_KE
  command: chage -d 0 "{{ item.name }}"
  loop: "{{ all_users[0].pobocka_KE }}"


