- name: Create standard_users
  tags: standard_users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    groups: "{{ item.group }}"
    password: "{{ item.password | password_hash('sha512') }}"
    state: present
  loop: "{{ all_users[0].standard_users }}"
  no_log: true

- name: Create admin_users
  tags: admin_users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment | default(omit) }}"
    groups: "{{ item.group }}"
    state: present
  loop: "{{ all_users[1].admin_users }}"

- name: Create avengers_users 
  tags: avengers _users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    groups: "{{ item.group }}"
    state: present
  loop: "{{ all_users[2].avengers_users }}"

