- name: Create a users for BRANCH_KE
  tags: KE branch_ke
  user:
    name:  "{{ item.name }}"
    home: "{{ item.home | default('/home/default') }}"
    shell: "{{ item.shell | default('omit') }}"
    comment: "{{ item.comment | default('omit') }}"
    group: "{{ item.group }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    password_expire_max: "{{ item.password_expire_max | default('omit') }}"
  loop: "{{ standard_user[0].branch_KE }}"

 
- name: Create a users for BRANCH_ZV
  tags: ZV branch_zv
  user:
    name:  "{{ item.name }}"
    home: "{{ item.home | default('/home/default') }}"
    shell: "{{ item.shell | default('omit') }}"
    comment: "{{ item.comment | default('omit') }}"
    group: "{{ item.group }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    password_expire_max: "{{ item.password_expire_max | default('omit') }}"
  loop: "{{ standard_user[1].branch_ZV }}"


- name: Force to change password for first login
  command: chage -d 0 "{{ item.name }}"
  loop: "{{ standard_user[0].branch_KE }}"


    
