- name: Delete unwanted_users standard_users
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ delete_unwanted_users[0].standard_users }}"

- name: Delete unwanted_users avengers_users
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ delete_unwanted_users[1].avengers_users }}"
  
