---
  - name: INSTALATION NFS AS A SERVER 
    hosts: centosserver
    become: true
    tasks:
   
    - name: INSTALL NFS-UTILS
      dnf:
        name:
          - nfs-utils
          - rpcbind
          - libnfsidmap
        state: present
      when: ansible_distribution == "CentOS"

    - name: START the NFS-SERVER
      service:
        name: nts-server
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: START the RPCBIND
      service:
        name: rpcbind
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: START the RPC-STATD
      service:
        name: rpc-statd
        state: started

    - name: START the nfs-idmapd
      servcice: 
        name: nfs-idmapd
        state: started

    
    - name: CREATE a DIR for SHARING 
      file:
        path: /shares
        owner: root
        group: root
        mode: 0777
        state: directory

    - name: MODY /etc/exports
      blockinfile:
        path: /etc/exports
        block: "/shares     *(rw,sync,no_root_squash)"

    - name: EXPORT the NFS SYSTEM
      shell:
        commands: exports -rv

    - name: CHANGE THE FIREWALL for NFS
      firewalld:
        port: "{{ item }}"
        state: present
        permanent: true
      loop: 
        - 2049/tcp
        - 2049/udp
        - 111/tcp
        - 111/udp
        - 32767/tcp
        - 32767/udp


    
        
