- name: Deny the default income traffic 
  ufw:
    default: deny
    direction: incoming
  when: ansible_distribution == "Debian"

- name: Allow deafult outoing traffic
  ufw: 
    default: allow
    direction: outgoing
  when: ansible_distribution == "Debian"


- name: Allow SSH protocol 
  ufw:
    rule: allow
    port: '22'
    proto: tcp 
  when: ansible_distribution == "Debian"


- name: Allow IP range of address to enter the SERVER
  ufw: 
    rule: allow
    src: 192.168.0.0/24
    proto: tcp
    port: '22'
  when: ansible_distribution == "Debian"

- name: Remove SSH port for everyone
  ufw:
    state: enabled
    rule: allow
    port: '22'
    proto: tcp 
    delete: true
  when: ansible_distribution == "Debian"
  notify: restart ufw
